USE marvash_MODB;

CREATE TABLE IF NOT EXISTS CATEGORY(
CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(40) NOT NULL,
MIN_AGE INT NOT NULL,
MAX_AGE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS TEAM(
TEAM_ID INT PRIMARY KEY AUTO_INCREMENT,
COLOR CHARACTER(6) NOT NULL,
NAME VARCHAR(40) NOT NULL,
COMP_NUM_MIN INT NOT NULL,
COMP_NUM_MAX INT NOT NULL,
RACE_TIME_MALE REAL,
RACE_TIME_FEMALE REAL
);

CREATE TABLE IF NOT EXISTS COMPETITION(
COMPETITION_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(40) NOT NULL,
RESULT_TYPE ENUM('SUM','BEST','HIGH_JUMP')
);

CREATE TABLE IF NOT EXISTS ATHLETE(
ATHLETE_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(40) NOT NULL,
SURNAME VARCHAR(40) NOT NULL,
DATE_OF_BIRTH DATE NOT NULL,
GENDER ENUM('MALE','FEMALE') NOT NULL,
COMP_NUM INT,
TEAM_ID INT,
CATEGORY_ID INT,
FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID)
ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ATHLETE_COMPETITION(
ATHLETE_ID INT,
COMPETITION_ID INT,
PLACEMENT INT,
SCORE INT,
PRIMARY KEY(ATHLETE_ID,COMPETITION_ID),
FOREIGN KEY(ATHLETE_ID) REFERENCES ATHLETE(ATHLETE_ID)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(COMPETITION_ID) REFERENCES COMPETITION(COMPETITION_ID)
ON DELETE CASCADE ON UPDATE CASCADE 
);

CREATE TABLE IF NOT EXISTS RESULT(
RESULT_ID INT PRIMARY KEY AUTO_INCREMENT,
ATHLETE_ID INT,
COMPETITION_ID INT,
RESULT_VALUE REAL NOT NULL,
MISTAKES INT,
FOREIGN KEY(ATHLETE_ID) REFERENCES ATHLETE_COMPETITION(ATHLETE_ID)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(COMPETITION_ID) REFERENCES ATHLETE_COMPETITION(COMPETITION_ID)
ON DELETE CASCADE ON UPDATE CASCADE 
);